name: 'init-job'
description: > 
  initialize job environment with environment variables
inputs:
  env-path:
    description: >-
      path to the configuration file of environment variables
    default: ./.github/.env
    required: true
        
runs:
  using: "composite"
  steps:
    - name: checkout current repo
      uses: actions/checkout@v2
    - name: load env
      run: |
        sed "" ${{ inputs.env-path }} >> $GITHUB_ENV
      shell: bash
