name: 'init-job'
description: > 
  initialize job environment with environment variables

inputs:
  env-path:
    description: >-
      path to the configuration file of environment variables
    default: ./.github/.env
    required: true
  github-pat:
    description: >
      Personal access token (PAT) used by actions/checkout@v2 
      to fetch the repository. Note that github token
      can be used only for the working directory. 
    required: true
        
runs:
  using: "composite"
  steps:
    - name: checkout current repo
      uses: actions/checkout@v2
    - name: load env
      run: |
        sed "" ${{ inputs.env-path }} >> $GITHUB_ENV
      shell: bash
    - name: add exception for current directory
      run: |
        git config --global --add safe.directory $(pwd)
      shell: bash
    - name: checkout tools repository
      uses: actions/checkout@v2
      with:
        repository:  ${{ env.CI-SCRIPT-REPO }}
        token: ${{ inputs.github-pat }}
        path: ${{ env.CI-SCRIPT-FOLDER-NAME }}
        ref: master
    - name: move files and update file rights
      run: |
        rm -fr ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}
        mkdir -p ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}
        mv ${{ env.CI-SCRIPT-FOLDER-NAME }} ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}/
        chmod -R +x ${{ env.CI-SCRIPT-WORKING-DIRECTORY }}/${{ env.CI-SCRIPT-FOLDER-NAME }}
      shell: bash
