name: 'init-job'
description: > 
  initialize job environment with environment variables

inputs:
  env-path:
    description: >-
      path to the configuration file of environment variables
    default: ./.github/.env
    required: true
  github-pat:
    description: >
      Personal access token (PAT) used by actions/checkout@v2 
      to fetch the repository. Note that github token
      can be used only for the working directory. 
    required: true
        
runs:
  using: "composite"
  steps:
    - name: checkout current repo
      uses: actions/checkout@v3
      with:
        path: main       
    - name: load project env
      run: |
        sudo sed '/^#/d' main/${{ inputs.env-path }} >> $GITHUB_ENV
      shell: bash
    - name: checkout tools repository
      uses: actions/checkout@v3
      with:
        repository:  ${{ env.CI-SCRIPT-REPO }}
        token: ${{ inputs.github-pat }}
        path: ${{ env.CI-SCRIPT-FOLDER-NAME }}
        ref: ter
    - name: load cicd env
      run: |
        sudo sed '/^#/d' ${{ env.CICD-ENV }} >> $GITHUB_ENV
      shell: bash
    - name: update file rights
      run: |
        sudo chmod -R +x *
      shell: bash
